# Maintainer: Mahosauru
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.5.0
      hooks:
        - id: trailing-whitespace
        - id: check-added-large-files
        - id: detect-private-key
        - id: end-of-file-fixer
        - id: check-ast
        - id: check-merge-conflict
        - id: check-yaml
